/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.exemplobuttongroup;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Marcos
 */
public class VendaComputador extends javax.swing.JFrame {

    /**
     * Creates new form VendaComputador
     */
    public VendaComputador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gruposo = new javax.swing.ButtonGroup();
        grupotipocomputador = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        tglwindows = new javax.swing.JToggleButton();
        tgllinux = new javax.swing.JToggleButton();
        confirmar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        rbopc = new javax.swing.JRadioButton();
        rbonotebook = new javax.swing.JRadioButton();
        rboservidor = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        chkmochila = new javax.swing.JCheckBox();
        chkteclado = new javax.swing.JCheckBox();
        chkmouse = new javax.swing.JCheckBox();
        chkheadset = new javax.swing.JCheckBox();
        cbotipohd = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstServicos = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        gruposo.add(tglwindows);
        tglwindows.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tglwindows.setText("WINDOWS");
        tglwindows.setActionCommand("WINDOWS");
        tglwindows.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglwindowsActionPerformed(evt);
            }
        });

        gruposo.add(tgllinux);
        tgllinux.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tgllinux.setText("LINUX");
        tgllinux.setActionCommand("LINUX");
        tgllinux.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgllinuxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(tglwindows, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tgllinux, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tgllinux, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tglwindows, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        confirmar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        confirmar.setText("CONFIRMAR");
        confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        grupotipocomputador.add(rbopc);
        rbopc.setText("PC");
        rbopc.setActionCommand("PC");

        grupotipocomputador.add(rbonotebook);
        rbonotebook.setText("Notebook");
        rbonotebook.setActionCommand("Notebook");

        grupotipocomputador.add(rboservidor);
        rboservidor.setText("Servidor");
        rboservidor.setActionCommand("Servidor");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rbopc)
                .addGap(54, 54, 54)
                .addComponent(rbonotebook)
                .addGap(37, 37, 37)
                .addComponent(rboservidor)
                .addGap(49, 49, 49))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbopc)
                    .addComponent(rbonotebook)
                    .addComponent(rboservidor))
                .addGap(36, 36, 36))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        chkmochila.setText("mochila");

        chkteclado.setText("teclado");

        chkmouse.setText("mouse");

        chkheadset.setText("headset");
        chkheadset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkheadsetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chkmochila)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(chkmouse)
                .addGap(31, 31, 31)
                .addComponent(chkheadset)
                .addGap(29, 29, 29)
                .addComponent(chkteclado)
                .addGap(18, 18, 18))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkmochila)
                    .addComponent(chkmouse)
                    .addComponent(chkheadset)
                    .addComponent(chkteclado))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        cbotipohd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo de HD:", "SSD120", "SSD240", "SSD1T" }));
        cbotipohd.setActionCommand("Tipo de HD:\nSSD120\nSSD240\nSSD1T");
        cbotipohd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbotipohdActionPerformed(evt);
            }
        });

        lstServicos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5", "Item 6", "Item 7" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstServicos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(confirmar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbotipohd, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbotipohd, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(confirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tglwindowsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglwindowsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tglwindowsActionPerformed

    private void tgllinuxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgllinuxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tgllinuxActionPerformed

    private void confirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarActionPerformed
        /**
         * if(tglwindows.isSelected()){ JOptionPane.showMessageDialog(this,
         * "Botão Windows selecionado"); }else if(tgllinux.isSelected()){
         * JOptionPane.showMessageDialog(this, "Botão Linux selecionado"); }
         * else{ JOptionPane.showMessageDialog(this, "Selecione um botão"); }
         */
        String retorno = gruposo.getSelection().getActionCommand();
        //JOptionPane.showMessageDialog(this, "Você selecionou: " + retorno);

        String tipoComputador = grupotipocomputador.getSelection().getActionCommand();
        //JOptionPane.showMessageDialog(this, "Você selecionou: " + retorno);

         String acessorios = " ";
        if (chkmochila.isSelected()) {
            acessorios += "Mochila " + ",";
        }
        if (chkmouse.isSelected()) {
            acessorios += "Mouse " + ",";
        }
        if (chkheadset.isSelected()) {
            acessorios += "Headset " + ",";
        }
        if (chkteclado.isSelected()) {
            acessorios += "Teclado " + ",";
        }
        JOptionPane.showMessageDialog(this, "Você selecionou: " + acessorios);
        int indice = cbotipohd.getSelectedIndex();
        if (indice > 0) {
            String tipoHD = cbotipohd.getSelectedItem().toString();
            JOptionPane.showMessageDialog(this, tipoHD);

        } else {
            JOptionPane.showMessageDialog(this, "Selecione um HD!");
        }

        //String itemJList = lstServicos.getSelectedValue();
        //JOptionPane.showMessageDialog(this, itemJlist);
        ArrayList<String> listaItens = (ArrayList<String>) lstServicos.getSelectedValuesList();
        //foreach
        String itensLista = " ";
        for (String item : listaItens) {
            itensLista += item + ", ";
        }
        JOptionPane.showMessageDialog(this, itensLista);
    }//GEN-LAST:event_confirmarActionPerformed

    private void chkheadsetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkheadsetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkheadsetActionPerformed

    private void cbotipohdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbotipohdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbotipohdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VendaComputador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VendaComputador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VendaComputador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VendaComputador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VendaComputador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbotipohd;
    private javax.swing.JCheckBox chkheadset;
    private javax.swing.JCheckBox chkmochila;
    private javax.swing.JCheckBox chkmouse;
    private javax.swing.JCheckBox chkteclado;
    private javax.swing.JButton confirmar;
    private javax.swing.ButtonGroup gruposo;
    private javax.swing.ButtonGroup grupotipocomputador;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lstServicos;
    private javax.swing.JRadioButton rbonotebook;
    private javax.swing.JRadioButton rbopc;
    private javax.swing.JRadioButton rboservidor;
    private javax.swing.JToggleButton tgllinux;
    private javax.swing.JToggleButton tglwindows;
    // End of variables declaration//GEN-END:variables

    private ArrayList<String> getSelectedValuesList() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
